apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: ai-api-integrator
  labels:
    app: ai-api-integrator
    component: api
    environment: production
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3001
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  selector:
    app: ai-api-integrator
    component: api

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: ai-api-integrator-staging
  labels:
    app: ai-api-integrator
    component: api
    environment: staging
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3001
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  selector:
    app: ai-api-integrator
    component: api

---
# Headless service for StatefulSet components (if needed)
apiVersion: v1
kind: Service
metadata:
  name: api-headless
  namespace: ai-api-integrator
  labels:
    app: ai-api-integrator
    component: api
spec:
  clusterIP: None
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: ai-api-integrator
    component: api
